from yellcorp/node-php5-builder:latest

LABEL maintainer="Jim Boswell <jimb@yellcorp.org>"
LABEL version=0.0.2
LABEL description="The Node 6.x + PHP-cli + Composer + Ruby + Sass combo from \
                   yellcorp/node-php5-builder, with Compass \
                   (http://compass-style.org/) added."

RUN gem install compass

CMD [ "sh" ]
